// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_TimePaused;
lv_obj_t * uic_SBPaused;
lv_obj_t * uic_PausedHeader;
lv_obj_t * uic_End;
lv_obj_t * uic_Resume;
lv_obj_t * uic_PausedScreen;
lv_obj_t * ui_PausedScreen;
lv_obj_t * ui_Resume;
lv_obj_t * ui_End;
lv_obj_t * ui_PausedHeader;
lv_obj_t * ui_SBPaused;
lv_obj_t * ui_TimePaused;

// event funtions

// build funtions

void ui_PausedScreen_screen_init(void)
{
    ui_PausedScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PausedScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PausedScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PausedScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Resume = lv_label_create(ui_PausedScreen);
    lv_obj_set_width(ui_Resume, 160);
    lv_obj_set_height(ui_Resume, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Resume, -85);
    lv_obj_set_y(ui_Resume, 0);
    lv_obj_set_align(ui_Resume, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Resume, "Resume");
    lv_obj_set_style_text_color(ui_Resume, lv_color_hex(0xF5F5F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Resume, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Resume, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Resume, &ui_font_Header1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Resume, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Resume, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Resume, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Resume, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Resume, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_End = lv_label_create(ui_PausedScreen);
    lv_obj_set_width(ui_End, 160);
    lv_obj_set_height(ui_End, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_End, 85);
    lv_obj_set_y(ui_End, 0);
    lv_obj_set_align(ui_End, LV_ALIGN_CENTER);
    lv_label_set_text(ui_End, "End");
    lv_obj_set_style_text_color(ui_End, lv_color_hex(0xF5F5F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_End, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_End, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_End, &ui_font_Header1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_End, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_End, lv_color_hex(0x274651), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_End, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_End, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_End, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_End, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_End, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PausedHeader = lv_label_create(ui_PausedScreen);
    lv_obj_set_width(ui_PausedHeader, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PausedHeader, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PausedHeader, 10);
    lv_obj_set_y(ui_PausedHeader, 10);
    lv_label_set_text(ui_PausedHeader, "Paused");
    lv_obj_set_style_text_color(ui_PausedHeader, lv_color_hex(0xF5F5F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PausedHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PausedHeader, &ui_font_Body2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SBPaused = lv_label_create(ui_PausedScreen);
    lv_obj_set_width(ui_SBPaused, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SBPaused, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SBPaused, 0);
    lv_obj_set_y(ui_SBPaused, -10);
    lv_obj_set_align(ui_SBPaused, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_SBPaused, "How Design Makes Us Think");
    lv_obj_set_style_text_color(ui_SBPaused, lv_color_hex(0x5D5D5D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SBPaused, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SBPaused, &ui_font_Body1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimePaused = lv_label_create(ui_PausedScreen);
    lv_obj_set_width(ui_TimePaused, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimePaused, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimePaused, 0);
    lv_obj_set_y(ui_TimePaused, 10);
    lv_obj_set_align(ui_TimePaused, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_TimePaused, "00:00");
    lv_obj_set_style_text_color(ui_TimePaused, lv_color_hex(0xF5F5F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TimePaused, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TimePaused, &ui_font_Body1, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_PausedScreen = ui_PausedScreen;
    uic_Resume = ui_Resume;
    uic_End = ui_End;
    uic_PausedHeader = ui_PausedHeader;
    uic_SBPaused = ui_SBPaused;
    uic_TimePaused = ui_TimePaused;

}

void ui_PausedScreen_screen_destroy(void)
{
    if(ui_PausedScreen) lv_obj_del(ui_PausedScreen);

    // NULL screen variables
    uic_PausedScreen = NULL;
    ui_PausedScreen = NULL;
    uic_Resume = NULL;
    ui_Resume = NULL;
    uic_End = NULL;
    ui_End = NULL;
    uic_PausedHeader = NULL;
    ui_PausedHeader = NULL;
    uic_SBPaused = NULL;
    ui_SBPaused = NULL;
    uic_TimePaused = NULL;
    ui_TimePaused = NULL;

}
