// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_PAUSEDSCREEN_H
#define UI_PAUSEDSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_PausedScreen
extern void ui_PausedScreen_screen_init(void);
extern void ui_PausedScreen_screen_destroy(void);
extern lv_obj_t * ui_PausedScreen;
extern lv_obj_t * ui_Resume;
extern lv_obj_t * ui_End;
extern lv_obj_t * ui_PausedHeader;
extern lv_obj_t * ui_SBPaused;
extern lv_obj_t * ui_TimePaused;
// CUSTOM VARIABLES
extern lv_obj_t * uic_PausedScreen;
extern lv_obj_t * uic_Resume;
extern lv_obj_t * uic_End;
extern lv_obj_t * uic_PausedHeader;
extern lv_obj_t * uic_SBPaused;
extern lv_obj_t * uic_TimePaused;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

