// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_RECORDINGSCREEN_H
#define UI_RECORDINGSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_RecordingScreen
extern void ui_RecordingScreen_screen_init(void);
extern void ui_RecordingScreen_screen_destroy(void);
extern lv_obj_t * ui_RecordingScreen;
extern lv_obj_t * ui_TimeRecording;
extern lv_obj_t * ui_SBRecording;
extern lv_obj_t * ui_RecordingHeader;
extern lv_obj_t * ui_Spinner1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_RecordingScreen;
extern lv_obj_t * uic_TimeRecording;
extern lv_obj_t * uic_SBRecording;
extern lv_obj_t * uic_RecordingHeader;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

