// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_RecordingHeader;
lv_obj_t * uic_SBRecording;
lv_obj_t * uic_TimeRecording;
lv_obj_t * uic_RecordingScreen;
lv_obj_t * ui_RecordingScreen;
lv_obj_t * ui_TimeRecording;
lv_obj_t * ui_SBRecording;
lv_obj_t * ui_RecordingHeader;
lv_obj_t * ui_Spinner1;

// event funtions

// build funtions

void ui_RecordingScreen_screen_init(void)
{
    ui_RecordingScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_RecordingScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RecordingScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RecordingScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeRecording = lv_label_create(ui_RecordingScreen);
    lv_obj_set_width(ui_TimeRecording, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeRecording, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TimeRecording, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimeRecording, "00:00");
    lv_obj_set_style_text_color(ui_TimeRecording, lv_color_hex(0x5FC9F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TimeRecording, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TimeRecording, &ui_font_Title1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SBRecording = lv_label_create(ui_RecordingScreen);
    lv_obj_set_width(ui_SBRecording, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SBRecording, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SBRecording, 0);
    lv_obj_set_y(ui_SBRecording, -10);
    lv_obj_set_align(ui_SBRecording, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_SBRecording, "How Design Makes Us Think");
    lv_obj_set_style_text_color(ui_SBRecording, lv_color_hex(0x5D5D5D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SBRecording, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SBRecording, &ui_font_Body1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RecordingHeader = lv_label_create(ui_RecordingScreen);
    lv_obj_set_width(ui_RecordingHeader, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RecordingHeader, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RecordingHeader, 10);
    lv_obj_set_y(ui_RecordingHeader, 10);
    lv_label_set_text(ui_RecordingHeader, "Recording");
    lv_obj_set_style_text_color(ui_RecordingHeader, lv_color_hex(0xF5F5F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RecordingHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RecordingHeader, &ui_font_Body2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinner1 = lv_spinner_create(ui_RecordingScreen, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 40);
    lv_obj_set_height(ui_Spinner1, 40);
    lv_obj_set_x(ui_Spinner1, -10);
    lv_obj_set_y(ui_Spinner1, 10);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Spinner1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR,
                                           _ui_theme_color_Black);
    ui_object_set_themeable_style_property(ui_Spinner1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_ARC_OPA,
                                           _ui_theme_alpha_Black);
    lv_obj_set_style_arc_width(ui_Spinner1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_object_set_themeable_style_property(ui_Spinner1, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR,
                                           _ui_theme_color_BlueClick);
    ui_object_set_themeable_style_property(ui_Spinner1, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_ARC_OPA,
                                           _ui_theme_alpha_BlueClick);
    lv_obj_set_style_arc_width(ui_Spinner1, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    uic_RecordingScreen = ui_RecordingScreen;
    uic_TimeRecording = ui_TimeRecording;
    uic_SBRecording = ui_SBRecording;
    uic_RecordingHeader = ui_RecordingHeader;

}

void ui_RecordingScreen_screen_destroy(void)
{
    if(ui_RecordingScreen) lv_obj_del(ui_RecordingScreen);

    // NULL screen variables
    uic_RecordingScreen = NULL;
    ui_RecordingScreen = NULL;
    uic_TimeRecording = NULL;
    ui_TimeRecording = NULL;
    uic_SBRecording = NULL;
    ui_SBRecording = NULL;
    uic_RecordingHeader = NULL;
    ui_RecordingHeader = NULL;
    ui_Spinner1 = NULL;

}
