// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_TotalPage;
lv_obj_t * uic_SBEnd;
lv_obj_t * uic_EndingPage;
lv_obj_t * uic_EndingPageHeader;
lv_obj_t * uic_SelectEndScreen;
lv_obj_t * ui_SelectEndScreen;
lv_obj_t * ui_EndingPageHeader;
lv_obj_t * ui_EndingPage;
lv_obj_t * ui_SBEnd;
lv_obj_t * ui_TotalPage;

// event funtions

// build funtions

void ui_SelectEndScreen_screen_init(void)
{
    ui_SelectEndScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SelectEndScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SelectEndScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SelectEndScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EndingPageHeader = lv_label_create(ui_SelectEndScreen);
    lv_obj_set_width(ui_EndingPageHeader, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_EndingPageHeader, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_EndingPageHeader, 10);
    lv_obj_set_y(ui_EndingPageHeader, 10);
    lv_label_set_text(ui_EndingPageHeader, "Ending Page");
    lv_obj_set_style_text_color(ui_EndingPageHeader, lv_color_hex(0xF5F5F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_EndingPageHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_EndingPageHeader, &ui_font_Body2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EndingPage = lv_roller_create(ui_SelectEndScreen);
    lv_roller_set_options(ui_EndingPage, "123", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_EndingPage, 110);
    lv_obj_set_width(ui_EndingPage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_EndingPage, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_EndingPage, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_EndingPage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_EndingPage, &ui_font_Title1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_EndingPage, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_EndingPage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_EndingPage, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_EndingPage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_EndingPage, lv_color_hex(0x5FC9F0), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_EndingPage, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_EndingPage, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_EndingPage, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_SBEnd = lv_label_create(ui_SelectEndScreen);
    lv_obj_set_width(ui_SBEnd, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SBEnd, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SBEnd, 0);
    lv_obj_set_y(ui_SBEnd, -10);
    lv_obj_set_align(ui_SBEnd, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_SBEnd, "How Design Makes Us Think");
    lv_obj_set_style_text_color(ui_SBEnd, lv_color_hex(0x5D5D5D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SBEnd, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SBEnd, &ui_font_Body1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TotalPage = lv_label_create(ui_SelectEndScreen);
    lv_obj_set_width(ui_TotalPage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TotalPage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TotalPage, 0);
    lv_obj_set_y(ui_TotalPage, -75);
    lv_obj_set_align(ui_TotalPage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TotalPage, "26 Pages");
    lv_obj_set_style_text_color(ui_TotalPage, lv_color_hex(0xF5F5F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TotalPage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TotalPage, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TotalPage, &ui_font_Body1, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_SelectEndScreen = ui_SelectEndScreen;
    uic_EndingPageHeader = ui_EndingPageHeader;
    uic_EndingPage = ui_EndingPage;
    uic_SBEnd = ui_SBEnd;
    uic_TotalPage = ui_TotalPage;

}

void ui_SelectEndScreen_screen_destroy(void)
{
    if(ui_SelectEndScreen) lv_obj_del(ui_SelectEndScreen);

    // NULL screen variables
    uic_SelectEndScreen = NULL;
    ui_SelectEndScreen = NULL;
    uic_EndingPageHeader = NULL;
    ui_EndingPageHeader = NULL;
    uic_EndingPage = NULL;
    ui_EndingPage = NULL;
    uic_SBEnd = NULL;
    ui_SBEnd = NULL;
    uic_TotalPage = NULL;
    ui_TotalPage = NULL;

}
