// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SELECTBOOKSCREEN_H
#define UI_SELECTBOOKSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SelectBookScreen
extern void ui_SelectBookScreen_screen_init(void);
extern void ui_SelectBookScreen_screen_destroy(void);
extern lv_obj_t * ui_SelectBookScreen;
extern lv_obj_t * ui_BookNames;
extern lv_obj_t * ui_SelectBookHeader;
// CUSTOM VARIABLES
extern lv_obj_t * uic_SelectBookScreen;
extern lv_obj_t * uic_BookNames;
extern lv_obj_t * uic_SelectBookHeader;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

