// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SUCCESSSCREEN_H
#define UI_SUCCESSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SuccessScreen
extern void ui_SuccessScreen_screen_init(void);
extern void ui_SuccessScreen_screen_destroy(void);
extern lv_obj_t * ui_SuccessScreen;
extern lv_obj_t * ui_MarkedIt;
extern lv_obj_t * ui_SuccessHeader;
extern lv_obj_t * ui_SBSuccess;
// CUSTOM VARIABLES
extern lv_obj_t * uic_SuccessScreen;
extern lv_obj_t * uic_MarkedIt;
extern lv_obj_t * uic_SuccessHeader;
extern lv_obj_t * uic_SBSuccess;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

