// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_SelectBookHeader;
lv_obj_t * uic_BookNames;
lv_obj_t * uic_SelectBookScreen;
lv_obj_t * ui_SelectBookScreen;
lv_obj_t * ui_BookNames;
lv_obj_t * ui_SelectBookHeader;

// event funtions

// build funtions

void ui_SelectBookScreen_screen_init(void)
{
    ui_SelectBookScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SelectBookScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SelectBookScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SelectBookScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BookNames = lv_roller_create(ui_SelectBookScreen);
    lv_roller_set_options(ui_BookNames, "The Creative Act: A Way of Being\nHow Design Makes Us Think\nDesigning Design",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_BookNames, 131);
    lv_obj_set_width(ui_BookNames, 516);   /// 1
    lv_obj_set_align(ui_BookNames, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_BookNames, lv_color_hex(0x5D5D5D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BookNames, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BookNames, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BookNames, &ui_font_Body1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BookNames, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BookNames, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BookNames, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BookNames, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_BookNames, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_BookNames, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_BookNames, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_BookNames, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_BookNames, lv_color_hex(0xF5F5F5), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BookNames, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BookNames, LV_TEXT_ALIGN_CENTER, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BookNames, &ui_font_Header2, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_BookNames, 20, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BookNames, lv_color_hex(0x274651), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BookNames, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_BookNames, LV_GRAD_DIR_NONE, LV_PART_SELECTED | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_BookNames, LV_PART_SELECTED | LV_STATE_DEFAULT, LV_STYLE_SHADOW_COLOR,
                                           _ui_theme_color_BlueHover);
    ui_object_set_themeable_style_property(ui_BookNames, LV_PART_SELECTED | LV_STATE_DEFAULT, LV_STYLE_SHADOW_OPA,
                                           _ui_theme_alpha_BlueHover);
    lv_obj_set_style_blend_mode(ui_BookNames, LV_BLEND_MODE_NORMAL, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_SelectBookHeader = lv_label_create(ui_SelectBookScreen);
    lv_obj_set_width(ui_SelectBookHeader, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SelectBookHeader, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SelectBookHeader, 10);
    lv_obj_set_y(ui_SelectBookHeader, 10);
    lv_label_set_text(ui_SelectBookHeader, "Select Book");
    lv_obj_set_style_text_color(ui_SelectBookHeader, lv_color_hex(0xF5F5F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SelectBookHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SelectBookHeader, &ui_font_Body2, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_SelectBookScreen = ui_SelectBookScreen;
    uic_BookNames = ui_BookNames;
    uic_SelectBookHeader = ui_SelectBookHeader;

}

void ui_SelectBookScreen_screen_destroy(void)
{
    if(ui_SelectBookScreen) lv_obj_del(ui_SelectBookScreen);

    // NULL screen variables
    uic_SelectBookScreen = NULL;
    ui_SelectBookScreen = NULL;
    uic_BookNames = NULL;
    ui_BookNames = NULL;
    uic_SelectBookHeader = NULL;
    ui_SelectBookHeader = NULL;

}
