// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_StartingPageCount;
lv_obj_t * uic_StartingPageHeader;
lv_obj_t * uic_SBSelectStart;
lv_obj_t * uic_SelectStartScreen;
lv_obj_t * ui_SelectStartScreen;
lv_obj_t * ui_SBSelectStart;
lv_obj_t * ui_StartingPageHeader;
lv_obj_t * ui_StartingPageCount;

// event funtions

// build funtions

void ui_SelectStartScreen_screen_init(void)
{
    ui_SelectStartScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SelectStartScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SelectStartScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SelectStartScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SBSelectStart = lv_label_create(ui_SelectStartScreen);
    lv_obj_set_width(ui_SBSelectStart, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SBSelectStart, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SBSelectStart, 0);
    lv_obj_set_y(ui_SBSelectStart, -10);
    lv_obj_set_align(ui_SBSelectStart, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_SBSelectStart, "How Design Makes Us Think");
    lv_obj_set_style_text_color(ui_SBSelectStart, lv_color_hex(0xF5F5F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SBSelectStart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SBSelectStart, &ui_font_Body1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StartingPageHeader = lv_label_create(ui_SelectStartScreen);
    lv_obj_set_width(ui_StartingPageHeader, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StartingPageHeader, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StartingPageHeader, 10);
    lv_obj_set_y(ui_StartingPageHeader, 10);
    lv_label_set_text(ui_StartingPageHeader, "Starting Page");
    lv_obj_set_style_text_color(ui_StartingPageHeader, lv_color_hex(0xF5F5F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_StartingPageHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_StartingPageHeader, &ui_font_Body2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StartingPageCount = lv_roller_create(ui_SelectStartScreen);
    lv_roller_set_options(ui_StartingPageCount, "00\n01\n02\n03", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_StartingPageCount, 110);
    lv_obj_set_width(ui_StartingPageCount, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_StartingPageCount, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_StartingPageCount, lv_color_hex(0x5D5D5D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_StartingPageCount, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_StartingPageCount, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_StartingPageCount, &ui_font_Title1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_StartingPageCount, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StartingPageCount, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_StartingPageCount, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StartingPageCount, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_StartingPageCount, lv_color_hex(0x5FC9F0), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_StartingPageCount, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_StartingPageCount, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StartingPageCount, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    uic_SelectStartScreen = ui_SelectStartScreen;
    uic_SBSelectStart = ui_SBSelectStart;
    uic_StartingPageHeader = ui_StartingPageHeader;
    uic_StartingPageCount = ui_StartingPageCount;

}

void ui_SelectStartScreen_screen_destroy(void)
{
    if(ui_SelectStartScreen) lv_obj_del(ui_SelectStartScreen);

    // NULL screen variables
    uic_SelectStartScreen = NULL;
    ui_SelectStartScreen = NULL;
    uic_SBSelectStart = NULL;
    ui_SBSelectStart = NULL;
    uic_StartingPageHeader = NULL;
    ui_StartingPageHeader = NULL;
    uic_StartingPageCount = NULL;
    ui_StartingPageCount = NULL;

}
