// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_SBSuccess;
lv_obj_t * uic_SuccessHeader;
lv_obj_t * uic_MarkedIt;
lv_obj_t * uic_SuccessScreen;
lv_obj_t * ui_SuccessScreen;
lv_obj_t * ui_MarkedIt;
lv_obj_t * ui_SuccessHeader;
lv_obj_t * ui_SBSuccess;

// event funtions

// build funtions

void ui_SuccessScreen_screen_init(void)
{
    ui_SuccessScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SuccessScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SuccessScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SuccessScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MarkedIt = lv_label_create(ui_SuccessScreen);
    lv_obj_set_width(ui_MarkedIt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MarkedIt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MarkedIt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MarkedIt, "MARKED IT!");
    lv_obj_set_style_text_color(ui_MarkedIt, lv_color_hex(0x5FC9F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MarkedIt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MarkedIt, &ui_font_Title_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SuccessHeader = lv_label_create(ui_SuccessScreen);
    lv_obj_set_width(ui_SuccessHeader, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SuccessHeader, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SuccessHeader, 10);
    lv_obj_set_y(ui_SuccessHeader, 10);
    lv_label_set_text(ui_SuccessHeader, "Success");
    lv_obj_set_style_text_color(ui_SuccessHeader, lv_color_hex(0xF5F5F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SuccessHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SuccessHeader, &ui_font_Body2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SBSuccess = lv_label_create(ui_SuccessScreen);
    lv_obj_set_width(ui_SBSuccess, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SBSuccess, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SBSuccess, 0);
    lv_obj_set_y(ui_SBSuccess, -10);
    lv_obj_set_align(ui_SBSuccess, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_SBSuccess, "How Design Makes Us Think");
    lv_obj_set_style_text_color(ui_SBSuccess, lv_color_hex(0x5D5D5D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SBSuccess, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SBSuccess, &ui_font_Body1, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_SuccessScreen = ui_SuccessScreen;
    uic_MarkedIt = ui_MarkedIt;
    uic_SuccessHeader = ui_SuccessHeader;
    uic_SBSuccess = ui_SBSuccess;

}

void ui_SuccessScreen_screen_destroy(void)
{
    if(ui_SuccessScreen) lv_obj_del(ui_SuccessScreen);

    // NULL screen variables
    uic_SuccessScreen = NULL;
    ui_SuccessScreen = NULL;
    uic_MarkedIt = NULL;
    ui_MarkedIt = NULL;
    uic_SuccessHeader = NULL;
    ui_SuccessHeader = NULL;
    uic_SBSuccess = NULL;
    ui_SBSuccess = NULL;

}
