// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_MarkLogo;
lv_obj_t * uic_StartScreen;
lv_obj_t * ui_StartScreen;
lv_obj_t * ui_MarkLogo;

// event funtions

// build funtions

void ui_StartScreen_screen_init(void)
{
    ui_StartScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_StartScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_StartScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StartScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_StartScreen, lv_color_hex(0xF5F5F5), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MarkLogo = lv_img_create(ui_StartScreen);
    lv_img_set_src(ui_MarkLogo, &ui_img_1563364657);
    lv_obj_set_width(ui_MarkLogo, LV_SIZE_CONTENT);   /// 249
    lv_obj_set_height(ui_MarkLogo, LV_SIZE_CONTENT);    /// 53
    lv_obj_set_align(ui_MarkLogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MarkLogo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_MarkLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    uic_StartScreen = ui_StartScreen;
    uic_MarkLogo = ui_MarkLogo;

}

void ui_StartScreen_screen_destroy(void)
{
    if(ui_StartScreen) lv_obj_del(ui_StartScreen);

    // NULL screen variables
    uic_StartScreen = NULL;
    ui_StartScreen = NULL;
    uic_MarkLogo = NULL;
    ui_MarkLogo = NULL;

}
