// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SELECTSTARTSCREEN_H
#define UI_SELECTSTARTSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SelectStartScreen
extern void ui_SelectStartScreen_screen_init(void);
extern void ui_SelectStartScreen_screen_destroy(void);
extern lv_obj_t * ui_SelectStartScreen;
extern lv_obj_t * ui_SBSelectStart;
extern lv_obj_t * ui_StartingPageHeader;
extern lv_obj_t * ui_StartingPageCount;
// CUSTOM VARIABLES
extern lv_obj_t * uic_SelectStartScreen;
extern lv_obj_t * uic_SBSelectStart;
extern lv_obj_t * uic_StartingPageHeader;
extern lv_obj_t * uic_StartingPageCount;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

