// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SELECTENDSCREEN_H
#define UI_SELECTENDSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SelectEndScreen
extern void ui_SelectEndScreen_screen_init(void);
extern void ui_SelectEndScreen_screen_destroy(void);
extern lv_obj_t * ui_SelectEndScreen;
extern lv_obj_t * ui_EndingPageHeader;
extern lv_obj_t * ui_EndingPage;
extern lv_obj_t * ui_SBEnd;
extern lv_obj_t * ui_TotalPage;
// CUSTOM VARIABLES
extern lv_obj_t * uic_SelectEndScreen;
extern lv_obj_t * uic_EndingPageHeader;
extern lv_obj_t * uic_EndingPage;
extern lv_obj_t * uic_SBEnd;
extern lv_obj_t * uic_TotalPage;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

