// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_STARTSCREEN_H
#define UI_STARTSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_StartScreen
extern void ui_StartScreen_screen_init(void);
extern void ui_StartScreen_screen_destroy(void);
extern lv_obj_t * ui_StartScreen;
extern lv_obj_t * ui_MarkLogo;
// CUSTOM VARIABLES
extern lv_obj_t * uic_StartScreen;
extern lv_obj_t * uic_MarkLogo;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

