// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_HoldToRecordHint;
lv_obj_t * uic_TimerHeader;
lv_obj_t * uic_SBTimer;
lv_obj_t * uic_Time;
lv_obj_t * uic_TimerScreen;
lv_obj_t * ui_TimerScreen;
lv_obj_t * ui_Time;
lv_obj_t * ui_SBTimer;
lv_obj_t * ui_TimerHeader;
lv_obj_t * ui_HoldToRecordHint;

// event funtions

// build funtions

void ui_TimerScreen_screen_init(void)
{
    ui_TimerScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_TimerScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TimerScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TimerScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Time = lv_label_create(ui_TimerScreen);
    lv_obj_set_width(ui_Time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Time, "00:00");
    lv_obj_set_style_text_color(ui_Time, lv_color_hex(0xF5F5F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Time, &ui_font_Title1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SBTimer = lv_label_create(ui_TimerScreen);
    lv_obj_set_width(ui_SBTimer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SBTimer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SBTimer, 0);
    lv_obj_set_y(ui_SBTimer, -10);
    lv_obj_set_align(ui_SBTimer, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_SBTimer, "How Design Makes Us Think");
    lv_obj_set_style_text_color(ui_SBTimer, lv_color_hex(0x5D5D5D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SBTimer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SBTimer, &ui_font_Body1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimerHeader = lv_label_create(ui_TimerScreen);
    lv_obj_set_width(ui_TimerHeader, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimerHeader, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimerHeader, 10);
    lv_obj_set_y(ui_TimerHeader, 10);
    lv_label_set_text(ui_TimerHeader, "Timer");
    lv_obj_set_style_text_color(ui_TimerHeader, lv_color_hex(0xF5F5F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TimerHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TimerHeader, &ui_font_Body2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HoldToRecordHint = lv_label_create(ui_TimerScreen);
    lv_obj_set_width(ui_HoldToRecordHint, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HoldToRecordHint, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HoldToRecordHint, 0);
    lv_obj_set_y(ui_HoldToRecordHint, 10);
    lv_obj_set_align(ui_HoldToRecordHint, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_HoldToRecordHint, "hold to record\ndouble click to pause");
    lv_obj_set_style_text_color(ui_HoldToRecordHint, lv_color_hex(0x5D5D5D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HoldToRecordHint, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_HoldToRecordHint, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HoldToRecordHint, &ui_font_Body2, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_TimerScreen = ui_TimerScreen;
    uic_Time = ui_Time;
    uic_SBTimer = ui_SBTimer;
    uic_TimerHeader = ui_TimerHeader;
    uic_HoldToRecordHint = ui_HoldToRecordHint;

}

void ui_TimerScreen_screen_destroy(void)
{
    if(ui_TimerScreen) lv_obj_del(ui_TimerScreen);

    // NULL screen variables
    uic_TimerScreen = NULL;
    ui_TimerScreen = NULL;
    uic_Time = NULL;
    ui_Time = NULL;
    uic_SBTimer = NULL;
    ui_SBTimer = NULL;
    uic_TimerHeader = NULL;
    ui_TimerHeader = NULL;
    uic_HoldToRecordHint = NULL;
    ui_HoldToRecordHint = NULL;

}
