// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_TIMERSCREEN_H
#define UI_TIMERSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_TimerScreen
extern void ui_TimerScreen_screen_init(void);
extern void ui_TimerScreen_screen_destroy(void);
extern lv_obj_t * ui_TimerScreen;
extern lv_obj_t * ui_Time;
extern lv_obj_t * ui_SBTimer;
extern lv_obj_t * ui_TimerHeader;
extern lv_obj_t * ui_HoldToRecordHint;
// CUSTOM VARIABLES
extern lv_obj_t * uic_TimerScreen;
extern lv_obj_t * uic_Time;
extern lv_obj_t * uic_SBTimer;
extern lv_obj_t * uic_TimerHeader;
extern lv_obj_t * uic_HoldToRecordHint;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

