// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_StartScreen_screen_init();
    ui_SelectBookScreen_screen_init();
    ui_SelectStartScreen_screen_init();
    ui_TimerScreen_screen_init();
    ui_PausedScreen_screen_init();
    ui_SelectEndScreen_screen_init();
    ui_SuccessScreen_screen_init();
    ui_RecordingScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_StartScreen);
}

void ui_destroy(void)
{
    ui_StartScreen_screen_destroy();
    ui_SelectBookScreen_screen_destroy();
    ui_SelectStartScreen_screen_destroy();
    ui_TimerScreen_screen_destroy();
    ui_PausedScreen_screen_destroy();
    ui_SelectEndScreen_screen_destroy();
    ui_SuccessScreen_screen_destroy();
    ui_RecordingScreen_screen_destroy();
}
