// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

///////////////////// SCREENS ////////////////////

#include "screens/ui_StartScreen.h"
#include "screens/ui_SelectBookScreen.h"
#include "screens/ui_SelectStartScreen.h"
#include "screens/ui_TimerScreen.h"
#include "screens/ui_PausedScreen.h"
#include "screens/ui_SelectEndScreen.h"
#include "screens/ui_SuccessScreen.h"
#include "screens/ui_RecordingScreen.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1563364657);    // assets/Start-Logo.png

// FONTS
LV_FONT_DECLARE(ui_font_Body1);
LV_FONT_DECLARE(ui_font_Body2);
LV_FONT_DECLARE(ui_font_Header1);
LV_FONT_DECLARE(ui_font_Header2);
LV_FONT_DECLARE(ui_font_Title1);
LV_FONT_DECLARE(ui_font_Title3);
LV_FONT_DECLARE(ui_font_Title_2);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
