// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_Gray[2] = {0x5D5D5D, 0x5D5D5D};
const ui_theme_variable_t _ui_theme_alpha_Gray[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_BlueHover[2] = {0x274651, 0x274651};
const ui_theme_variable_t _ui_theme_alpha_BlueHover[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_BlueClick[2] = {0x5FC9F0, 0x5FC9F0};
const ui_theme_variable_t _ui_theme_alpha_BlueClick[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_White[2] = {0xF5F5F5, 0xF5F5F5};
const ui_theme_variable_t _ui_theme_alpha_White[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_Black[2] = {0x000000, 0x000000};
const ui_theme_variable_t _ui_theme_alpha_Black[2] = {255, 255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

